### ISSUE TITLE
As a possible Investor, I want to see a wireframe of the possible web application so that I can decide whether or not to invest in the web-applcation 

### ISSUE THREAD

**Issue by Alex-primo** [xlab-classes/cse442-spring2022-team-the-squad#12]
The purpose of these tests are to have users know that they can successfully view the wireframe and the design.

Test 1:
1-Go to the figma page for the wireframe: https://www.figma.com/file/Z7uFU8Rc1ipvx8zFegM1tG/Blabbr-Mockup?node-id=0%3A1 .
2-Click on the button that plays the figma wireframe.
3-Check if the wireframe contains all of your expected functionalities.

Test 2:
1-Go to Figma and go the page for the specific wireframe.
2-Manually go to each element.
3-Check if there is all the possible elements or user functionalities design as par your personal requirements.

**Comment by refatull** [comment]
Test 1:
1-Go to the figma page for the wireframe .
2-Click on the button that plays the figma wireframe. 
3-Check if the wireframe contains all of your expected functionalities.

Test 2:
1-Go to Figma and go the page for the specific wireframe. 
2-Manually go to each element. 
3-Check if there is all the possible elements or user functionalities design as par your personal requirements.
