### ISSUE TITLE
Figma - Create the "Registration" page

### ISSUE THREAD

**Issue by twestpfa** [xlab-classes/cse442-spring2022-team-the-squad#14]
Task Tests
*Test 1*
- Open wireframe
- Go to main landing page
- Click on the Registration button
- Enter valid user credentials
- Click submit button
- Verify that the user is brought to a logged in chat page with their new account

*Test 2*
- Open wireframe
- Go to main landing page
- Click on the Registration button
- Click on the "log-in" button for a user who already has an account
- Verify that the user is brought to the log-in page

*Test 3*
- Open wireframe
- Go to main landing page
- Click on the Registration button
- Enter the user credentials, where the username is that of an already existing user
- Click the submit button
- Verify the page displays a message that the username is already taken
- Verify the page remains on the submit page and does not allow account creation

**Comment by refatull** [comment]
Open wireframe
Go to main landing page
Click Registration
Enter credentials 
Verify that that your credentials work
